### ISSUE TITLE
Git not pulling latest master

### ISSUE THREAD

**Issue by kmcgain** [Inedo/inedox-git#17]
BuildMaster 5.6.11
Git extension 5.6.5

When running a tag or get source command the latest commit on master is not being pulled. It cloned ok, but it seems the subsequent update commands are not having any effect.

Example call:
```
Git::Git-Tag
(
     Credentials: $ApplicationName,
     Tag: $ApplicationName.$ReleaseNumber.$PackageNumber,
     Branch: master,
     RecurseSubmodules: true
);
```

The log:

> Getting source from 'URL_TO_MY_REPO' on 'master' branch...
> Using LocalAgent agent on SOME_MACHINE
> No executable path specified, using built-in Git library...
> Using repository at 'D:\Apps\BuildMaster\_SVCTMP\GitWorkspaces\MY_REPO\'...
> Fetching commits from origin...
> Connecting as user 'MY_CREDENTIAL_USERNAME'...
> Resetting the index and working tree to master...
> Current commit is NOT_THE_LATEST_COMMIT.
> Get source complete.

**Comment by kmcgain** [comment]
It seems this was also noticed on a previous build: http://inedo.com/support/questions/6167

**Comment by apxltd** [comment]
We can certainly look at how libgit2 is handling it, but you may want to use git.exe instead.
