### ISSUE TITLE
FIX: General Tag operation does not resolve credentials correctly

### ISSUE THREAD

**Issue by jrasch** [Inedo/inedox-git#22]
It looks like the `ScriptAlias` value was changed accidentally.

**Comment by BenLubar** [comment]
There were some class names that overlapped:

https://github.com/Inedo/inedox-git/commit/b02f9f20abbfeafafc1bd889d97627ad0ab2d825

**Comment by jrasch** [comment]
Sorry I meant to put `ScriptAlias` for the `Credentials` property.

**Comment by BenLubar** [comment]
The ScriptAlias for Credentials in the GeneralGetSourceOperation is also wrong.
