### ISSUE TITLE
Unsupported sort strategy. Only 'Topological', 'Time', or 'Topological | Time' are allowed

### ISSUE THREAD

**Issue by MarkRobertJohnson** [Inedo/inedox-git#58]
The pull request that changed "SortBy = CommitSortStrategies.None", is now causing the following error:

(500) Server Error
Unsupported sort strategy. Only 'Topological', 'Time', or 'Topological | Time' are allowed. Parameter name: queryFilter
For more information, visit the Error Log Page.

Need to revert back to "SortBy = CommitSortStrategies.Time" in GitRaftRepositoryBase.cs

**Comment by BenLubar** [comment]
Fixed in 6cd44a6574bbbd57fa171850f0007dfbe53ccfdf
