### ISSUE TITLE
Missing GitHub variables

### ISSUE THREAD

**Issue by jsharbison** [Inedo/inedox-git#62]
What variables are currently expected to be available for use in GitHub webhook triggered executions? Based on the documentation I believe that the following should be available.

- $CommitHash and/or $CommitId

- $Branch

- %GitHub

And that the following should be coming soon

- $Repository

- $CommitUser

However, when I trigger a plan to print these variables out I am seeing only $Branch and $Repository. Is the documentation a bit off and some of these variables are still being developed or is there an actual defect somewhere? Perhaps I have the wrong names?

**Comment by gdivis** [comment]
Hi Josh-

The documentation in this GitHub project is a bit off. It looks to have been written prior to release. Currently supported webhook variables are only $Branch, $Repository, and $CommitHash (see [here](https://inedo.com/support/documentation/buildmaster/core-concepts/builds-and-ci#ci-plans)).

Webhooks are not currently handled in the Git extension, so adding more variables will require a product update. Fortunately, we are planning to release BuildMaster 6.1.1 pretty soon. Could you re-file this ticket [on our website](https://inedo.com/support/submit-ticket)? That way we can prioritize it for inclusion in the upcoming maintenance release.

Also, feel free to list all of the variables you would like included - we decided to scale back what was included with 6.1.0 until we got actual feedback from what variables people wanted, but unfortunately the docs here didn't get that update :(
