### ISSUE TITLE
Built in Git client does not work with Git LFS

### ISSUE THREAD

**Issue by gdivis** [Inedo/inedox-git#8]
Doesn't seem to be supported natively by libgitsharp, so maybe figure out a way to show a warning if it's needed?

**Comment by gdivis** [comment]
When I tested this, the git-lfs process just hung. My guess was that it was either waiting for input, or waiting for one of the stderr/stdout pipes to be closed, but I haven't tried to reproduce this on my workstation yet. Can you take a look?

**Comment by BenLubar** [comment]
https://github.com/Inedo/inedox-git/commit/23c2dbc7851a3f2f4a2535e59b983a81107076af

It's hacky because Filter doesn't have any reference to the CredentialHelper for the repository, but it works for the test cases I tried.
